apiVersion: apps/v1
kind: Deployment
metadata:
  name: multistage
spec:
  selector:
    matchLabels:
      app: multistage
  template:
    metadata:
      labels:
        app: multistage
    spec:
      containers:
      - name: multistage
        image: public.ecr.aws/g5i1d7r1/navya114:latest
        ports:
        - containerPort: 8080
        volumeMounts: 
        - name: volume-pv
          mountPath: /usr/local/tomcat/webapps/
      volumes: 
      - name: volume-pv
        persistentVolumeClaim:
          claimName: multistage-pvc
      imagePullSecrets:      
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: multistage
spec:
  type: NodePort
  selector:
    app: multistage
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: multistage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: static
  hostPath:
    path: /opt/multistage


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multistage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: static
  resources:
    requests:
      storage: 1Gi
