apiVersion: apps/v1
kind: Deployment
metadata:
  name: multistage
spec:
  selector:
    matchLabels:
      app: multistage
  template:
    metadata:
      labels:
        app: multistage
    spec:
      containers:
      - name: multistage
        image: public.ecr.aws/g5i1d7r1/navya114:1.0.$BUILD_NUMBER'
        ports:
        - containerPort: 8080
#        volumeMounts: 
#       - name: volume-pv
#          mountPath: /usr/local/tomcat/webapps
#     volumes: 
#     - name: volume-pv
#       persistentVolumeClaim:
#         claimName: multistage-pvc
      imagePullSecrets:      
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: multistage
spec:
  type: NodePort
  selector:
    app: multistage
  ports:
  - port: 8080
    targetPort: 8080

